[tox]
envlist =
    py{311,312,313,314}-django52
    py{312,313,314}-django60

[testenv]
allowlist_externals = ./manage.py
commands = ./manage.py test tests --no-input {posargs}
deps =
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1

[testenv:coverage]
allowlist_externals = ./manage.py
deps =
    Django>=6.0,<6.1
    coverage
commands =
    coverage run ./manage.py test tests --no-input
    coverage report
    coverage html
