name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
      - uses: actions/cache@v2
        id: tox-cache
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ matrix.python-version }}-{{ hashFiles('tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-${{ matrix.python-version }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pip tox
      - name: Run Lint
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          black: ${{ matrix.python-version != '2.7' && matrix.python-version != '3.5' }}
          flake8: true
          git_email: "lint-action@client-secrets.com"
          auto_fix: true
      - name: Run test
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}